export const EVENTS = [
  {
    id: 0,
    name: 'Techno Night #12',
    venue: 'Club Rubín',
    bg: '#e8eaf6',
    emoji: '🎵',
    date: 'Fri 18 Apr',
    time: '10:00pm',
    price: '150 CZK',
    category: 'party',
    badge: 'hot',
    desc: "The best techno night of the month. 4h DJ set, bar open until 4am. Don't miss it.",
    attendees: [
      { init: 'M', bg: '#c5cae9', tc: '#1a237e', name: 'Mat', uni: 'TBU · France', flag: '🇫🇷' },
      { init: 'J', bg: '#b2dfdb', tc: '#004d40', name: 'Jana K.', uni: 'TBU · Czech', flag: '🇨🇿' },
      { init: 'A', bg: '#ffccbc', tc: '#bf360c', name: 'Andrea L.', uni: 'TBU · Spain', flag: '🇪🇸' },
      { init: 'K', bg: '#fff9c4', tc: '#f57f17', name: 'Karim B.', uni: 'TBU · Morocco', flag: '🇲🇦' },
      { init: 'S', bg: '#fce4ec', tc: '#880e4f', name: 'Sofia R.', uni: 'TBU · Italy', flag: '🇮🇹' },
      { init: 'L', bg: '#dcedc8', tc: '#33691e', name: 'Lena W.', uni: 'TBU · Germany', flag: '🇩🇪' },
    ],
  },
  {
    id: 1,
    name: 'Thursday Happy Hour',
    venue: 'Bar Panorama',
    bg: '#e3f2fd',
    emoji: '🍺',
    date: 'Thu 17 Apr',
    time: '8:00pm',
    price: '80 CZK',
    category: 'party',
    badge: '',
    desc: '2-for-1 beers until 10pm. Popular with TBU students. Good music and good vibes.',
    attendees: [
      { init: 'L', bg: '#dcedc8', tc: '#33691e', name: 'Lena W.', uni: 'TBU · Germany', flag: '🇩🇪' },
      { init: 'P', bg: '#bbdefb', tc: '#1565c0', name: 'Pedro M.', uni: 'TBU · Portugal', flag: '🇵🇹' },
    ],
  },
  {
    id: 2,
    name: 'Erasmus International Night',
    venue: 'Erasmus Zlín',
    bg: '#ede7f6',
    emoji: '🎤',
    date: 'Sat 19 Apr',
    time: '9:00pm',
    price: 'Free',
    category: 'party',
    badge: 'free',
    desc: 'Monthly Erasmus party. Meet students from all over the world. Free entry with TBU student card.',
    attendees: [
      { init: 'K', bg: '#fff9c4', tc: '#f57f17', name: 'Karim B.', uni: 'TBU · Morocco', flag: '🇲🇦' },
      { init: 'S', bg: '#fce4ec', tc: '#880e4f', name: 'Sofia R.', uni: 'TBU · Italy', flag: '🇮🇹' },
      { init: 'A', bg: '#ffccbc', tc: '#bf360c', name: 'Andrea L.', uni: 'TBU · Spain', flag: '🇪🇸' },
      { init: 'J', bg: '#b2dfdb', tc: '#004d40', name: 'Jana K.', uni: 'TBU · Czech', flag: '🇨🇿' },
    ],
  },
  {
    id: 3,
    name: 'TBU Football Match',
    venue: 'TBU Sports Ground',
    bg: '#e8f5e9',
    emoji: '⚽',
    date: 'Wed 16 Apr',
    time: '6:00pm',
    price: 'Free',
    category: 'sport',
    badge: 'free',
    desc: 'Weekly open football game. All levels welcome. Bring water and good energy.',
    attendees: [
      { init: 'A', bg: '#dcedc8', tc: '#33691e', name: 'Adam P.', uni: 'TBU · Czech', flag: '🇨🇿' },
      { init: 'R', bg: '#b2dfdb', tc: '#004d40', name: 'Radek M.', uni: 'TBU · Czech', flag: '🇨🇿' },
    ],
  },
  {
    id: 4,
    name: 'Open Basketball 3v3',
    venue: 'TBU Gym',
    bg: '#e3f2fd',
    emoji: '🏀',
    date: 'Sat 19 Apr',
    time: '2:00pm',
    price: 'Free',
    category: 'sport',
    badge: 'new',
    desc: 'First edition of the 3v3 tournament. Sign up solo or with a team. Prizes for top 3.',
    attendees: [
      { init: 'N', bg: '#bbdefb', tc: '#1565c0', name: 'Nikola H.', uni: 'TBU · Czech', flag: '🇨🇿' },
    ],
  },
]

export const RESTAURANTS = [
  {
    id: 0,
    name: 'Pizzeria Modrá Hvězda',
    emoji: '🍕',
    bg: '#fff3e0',
    cuisine: 'Italian · Pizza',
    dist: '120m from TBU',
    rating: 4.2,
    hours: '11:00 – 23:00',
    desc: 'Best pizza in Zlín. Show your TBU card for 20% off. Great for group dinners.',
    tags: ['Italian', 'Student deal', 'Open now'],
    slots: ['12:00', '13:00', '19:00', '20:00', '21:00', '22:00'],
  },
  {
    id: 1,
    name: 'Asian Garden',
    emoji: '🍜',
    bg: '#e8f5e9',
    cuisine: 'Asian · Noodles',
    dist: '400m from TBU',
    rating: 4.8,
    hours: '11:30 – 22:00',
    desc: 'Authentic Asian cuisine. Ramen, dumplings, baos. Best value in town for students.',
    tags: ['Asian', 'Budget friendly'],
    slots: ['12:00', '13:00', '18:30', '19:30', '20:30'],
  },
  {
    id: 2,
    name: 'Steakhouse Zlín',
    emoji: '🥩',
    bg: '#fbe9e7',
    cuisine: 'Grill · Steakhouse',
    dist: '600m from TBU',
    rating: 4.4,
    hours: '12:00 – 23:00',
    desc: 'Premium steaks and grill. Perfect for group events and special occasions.',
    tags: ['Grill', 'Group bookings'],
    slots: ['19:00', '20:00', '21:00'],
  },
]

export const NOTIFICATIONS = [
  { id: 0, emoji: '🎉', bg: '#e8eaf6', text: '<b>Jana K.</b> and 3 others just joined <b>Techno Night #12</b>', time: '2 min ago', unread: true },
  { id: 1, emoji: '🎁', bg: '#e8f5e9', text: 'New giveaway — win <b>2 free entries</b> to Club Rubín tonight', time: '15 min ago', unread: true },
  { id: 2, emoji: '🍕', bg: '#fff3e0', text: '<b>Pizzeria Modrá Hvězda</b> — 20% student discount this week only', time: '1h ago', unread: true },
  { id: 3, emoji: '⚽', bg: '#e8f5e9', text: 'New event in <b>Sport</b> — TBU Football Match this Wednesday', time: '3h ago', unread: false },
  { id: 4, emoji: '🎵', bg: '#e8eaf6', text: '<b>Karim B.</b> also joined <b>Erasmus Night</b>', time: '5h ago', unread: false },
  { id: 5, emoji: '🏀', bg: '#fff8e1', text: 'Reminder: <b>Open Basketball 3v3</b> is tomorrow at 2pm', time: 'Yesterday', unread: false },
]
